import api, { getLinks } from '../api'
import { me } from '../initial_state'

//

export const ALBUMS_FETCH_REQUEST = 'ALBUMS_FETCH_REQUEST'
export const ALBUMS_FETCH_SUCCESS = 'ALBUMS_FETCH_SUCCESS'
export const ALBUMS_FETCH_FAIL = 'ALBUMS_FETCH_FAIL'

export const ALBUMS_CREATE_REQUEST = 'ALBUMS_CREATE_REQUEST'
export const ALBUMS_CREATE_SUCCESS = 'ALBUMS_CREATE_SUCCESS'
export const ALBUMS_CREATE_FAIL = 'ALBUMS_CREATE_FAIL'

export const ALBUMS_REMOVE_REQUEST = 'ALBUMS_REMOVE_REQUEST'
export const ALBUMS_REMOVE_SUCCESS = 'ALBUMS_REMOVE_SUCCESS'
export const ALBUMS_REMOVE_FAIL = 'ALBUMS_REMOVE_FAIL'